import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Box, Typography } from "@mui/material";
import { NextPageWithLayout } from "./_app";
import { ReactElement } from "react";
import DefaultLayout from "@/layouts/Default/Default.layout";
import CardProduct from "@/features/CardProduct/CardProduct";
import { GetServerSideProps } from "next";
import { wrapper } from "@/redux/store";
import {
  getListOfProducts,
  getRunningQueriesThunkSetService,
  useGetListOfProductsQuery,
} from "@/services/productSetServices/productSetServices";
import handleSSRIsMobile from "@/utils/SSR/handleSSRIsMobile";

export const getServerSideProps: GetServerSideProps =
  wrapper.getServerSideProps((store) => async (ctx) => {
    handleSSRIsMobile(ctx.req, store);
    try {
      store.dispatch(getListOfProducts.initiate());
      const query = getRunningQueriesThunkSetService();
      await Promise.all(store.dispatch(query));
      return { props: {} };
    } catch (error) {
      return {
        props: {},
      };
    }
  });

const Home: NextPageWithLayout = () => {
  const { data } = useGetListOfProductsQuery();
  return (
    <>
      <Head>
        <title>DB custome wear</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box mb="32px">
        <Typography variant="h2" align="center" p="1rem">
          Temporada Autumn Winter
        </Typography>
        <Box height="16.93244rem" width="100%" position="relative" top="0">
          <Image src="/headerHome.jpg" fill alt="" />
          <Box
            display="flex"
            justifyContent="center"
            alignItems="center"
            bgcolor="rgba(0, 0, 0, 0.7)"
            p="1rem .5rem"
            position="absolute"
            bottom="0%"
            zIndex="999"
          >
            <Typography variant="h1" color="white">
              Ropa de pole dance para hombres y mujeres.
            </Typography>
          </Box>
        </Box>
        <Typography variant="h2" align="center" p="1rem">
          Nuestros Sets
        </Typography>
        {!!data?.length &&
          data.map((set) => (
            <CardProduct
              id={set.id}
              title={set.name}
              price={`${set.price || "Consultar"}`}
              img={set.images[0]} // arreglar imagen
              info={"2 colores - envio a toda españa."} // e.colors => formatear texto
              subTitle={set.season} // temporada
              key={set.name}
            />
          ))}
      </Box>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <DefaultLayout>{page}</DefaultLayout>;
};

export default Home;
