import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Box, Typography } from "@mui/material";
import { NextPageWithLayout } from "./_app";
import { ReactElement } from "react";
import DefaultLayout from "@/layouts/Default/Default.layout";
import CardProduct from "@/features/CardProduct/CardProduct";

const Home: NextPageWithLayout = () => (
  <>
    <Head>
      <title>DB custome wear</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Box mb="32px">
      <Typography variant="h2" align="center" p="1rem">
        Temporada Autumn Winter
      </Typography>
      <Box height="16.93244rem" width="100%" position="relative" top="0">
        <Image src="/headerHome.jpg" fill alt="" />
        <Box
          display="flex"
          justifyContent="center"
          alignItems="center"
          bgcolor="rgba(0, 0, 0, 0.7)"
          p="1rem .5rem"
          position="absolute"
          bottom="0%"
          zIndex="999"
        >
          <Typography variant="h1" color="white">
            Ropa de pole dance para hombres y mujeres.
          </Typography>
        </Box>
      </Box>
      <Typography variant="h2" align="center" p="1rem">
        Nuestros Sets
      </Typography>
      <CardProduct
        title={"Titulo"}
        price={"2000 pesos"}
        img={"este es el alt de la img cambiar prop por su respectivo objeto"}
        info={"2 colores - envio a toda españa."}
        subTitle={"Temporada 2000"}
      />
    </Box>
  </>
);

Home.getLayout = function getLayout(page: ReactElement) {
  return <DefaultLayout>{page}</DefaultLayout>;
};

export default Home;
